package dev.bwr.core;

/**
 * Immutable snapshot of everything the reactor model holds.
 *
 * <p>Per SPEC section 0 this single record serves three consumers: NBT
 * persistence, client sync, and the CC:Tweaked peripheral readout.
 * {@code ReactorCore} produces it via {@code toState()} and restores from it
 * via {@code fromState()}. The core never touches NBT.
 *
 * <p>All fields are plain doubles or double arrays. Nothing here imports
 * Minecraft, by design and by build configuration.
 *
 * <p><b>Units are explicit in field names.</b> Do not add a field whose unit is
 * ambiguous.
 *
 * <p><b>There is exactly one constructor, the canonical one, and there must
 * never be a second.</b> A shorter compatibility overload defaulting the newest
 * components used to live here so the tree kept compiling while the persistence
 * layer caught up, and it was a landmine: any caller that bound to it — the NBT
 * reader above all — silently got {@code scramActive == false} and un-scrammed
 * a saved reactor. Adding a component is <em>supposed</em> to break every call
 * site. A call site that still compiles after a component is added is a call
 * site that has quietly stopped persisting something, and that is precisely how
 * {@code hydrogenKg}, the protective oxide film and the peak fuel temperature
 * each went missing in turn.
 *
 * @param neutronPower       prompt fission power, fraction of rated (1.0 = rated)
 * @param precursors         delayed neutron precursor concentrations, six groups
 * @param sourceStrength     startup neutron source, in the same fractional units
 *                           as {@code neutronPower} per second. Non-zero is what
 *                           gives a shutdown core a finite count rate.
 * @param decayHeatFraction  decay heat, fraction of rated. Additive to fission power.
 * @param decayGroups        decay heat group inventories for the sum-of-exponentials fit
 * @param fuelTempC          volume-average fuel temperature, degrees C
 * @param cladTempC          average cladding temperature, degrees C
 * @param peakCladTempC      peak cladding temperature ever reached, degrees C.
 *                           Drives quench-spike branching; never decreases.
 * @param peakFuelTempC      peak fuel temperature ever reached, degrees C. Never
 *                           decreases, and it is the model's record of how close
 *                           the fuel came to melting —
 *                           {@code FuelThermal.getPeakFuelTemperatureFractionOfMelt()}
 *                           is computed from it and nothing else. It cannot be
 *                           reconstructed from the fields around it: heat flows
 *                           fuel to clad, so peak fuel is always strictly above
 *                           peak clad, and the restore used to floor it at
 *                           {@code max(peakCladTempC, fuelTempC)} — a floor that
 *                           always loses. A core that touched 2400 degC and then
 *                           cooled came back reporting a peak of about 290, so
 *                           every save quietly un-melted the fuel.
 * @param oxidationFraction  cumulative zirconium oxidation, 0..1. Never decreases.
 * @param hydrogenKg         hydrogen generated by Zr-water oxidation so far, kg.
 *                           Persisted in its own right rather than recomputed from
 *                           {@code oxidationFraction}: the two are stoichiometrically
 *                           linked but the containment consumer counts kilograms, and
 *                           dropping this field silently reset the counter on reload.
 * @param protectiveOxideArealKgPerM2
 *                           the protective oxide film as reacted zirconium per unit
 *                           area, kg/m2. Deliberately <em>not</em> monotonic — a quench
 *                           cracks it, and that cracking is what produces the spike.
 *                           It therefore cannot be reconstructed from
 *                           {@code oxidationFraction}, and omitting it cancelled an
 *                           in-progress quench spike across a save.
 * @param coolantTempC       bulk coolant temperature, degrees C
 * @param pressurePsig       reactor steam dome pressure, psig
 * @param voidFraction       core-average void fraction, 0..1
 * @param coreInletEnthalpyKJPerKg
 *                           the lagged core inlet enthalpy, kJ/kg — the void
 *                           model's only memory, and the second of the two
 *                           lagged thermal-hydraulic states beside
 *                           {@code voidFraction}. It has to be enthalpy rather
 *                           than subcooling: saturation enthalpy moves with
 *                           pressure instantly while the water already in the
 *                           downcomer keeps what it left with, and that gap is
 *                           the prompt void collapse. It cannot be
 *                           reconstructed from the fields around it, because a
 *                           reconstruction can only ever put it at the
 *                           <em>equilibrium</em> for the restored operating
 *                           point, and a core caught mid-transient is by
 *                           definition not there — the recirculation transit
 *                           has not finished. That reconstruction is what the
 *                           restore used to do, and it came back with a
 *                           different axial void profile: boiling boundary 0.66
 *                           against 0.19 on a scrammed core, which changed the
 *                           nodal flux shape, the per-rod flux weights and
 *                           therefore {@code reactivityTotal}.
 *                           Zero means a save that predates this component, on
 *                           which the restore falls back to the old equilibrium
 *                           reconstruction — the behaviour that save already had.
 * @param coreFlowFraction   core flow, fraction of rated
 * @param waterLevelIn       vessel level on the instrument-zero scale, inches
 * @param xenon              Xe-135 concentration, arbitrary consistent units
 * @param iodine             I-135 concentration, arbitrary consistent units
 * @param boronPpm           dissolved boron from SLC injection, ppm
 * @param burnupMwdPerTonne  core-average burnup, MWd/tonne
 * @param rodPositionsNotches       physical travel in notch units, 0..24; empty in legacy snapshots
 * @param rodNotches         per-rod notch position, 0..24 index (FCD label = index * 2)
 * @param accumulatorCharge  per-CRD accumulator charge, 0..1
 * @param reactivityTotal    net reactivity this tick, dk/k
 * @param betaEff            flux-weighted effective delayed neutron fraction
 * @param promptLifetime     effective prompt neutron lifetime, seconds
 * @param rodFluxWeights     the per-rod relative flux weight the nodal solve last
 *                           produced, mean 1.0, one entry per control rod. This is
 *                           the third frozen output of that solve, beside
 *                           {@code betaEff} and {@code promptLifetime} above, and
 *                           it is here for the same reason they are: the solve runs
 *                           once every {@link CoreConfig#nodalSolveIntervalTicks}
 *                           ticks — 1 Hz by default — so a snapshot closes its
 *                           reactivity balance on weights up to a second old, while
 *                           a restore that re-solves closes the same balance on
 *                           freshly solved ones. Those two weightings are not the
 *                           same: on a core drifting after a scram all 177 of 177
 *                           differed, by up to a part in 250, and
 *                           {@code RodWorth.totalInsertedWorthDkOverK} sums that
 *                           difference over every rod into a {@code reactivityTotal}
 *                           an ulp or two away from the one recorded beside it — a
 *                           snapshot that cannot reproduce itself. Nothing can
 *                           reconstruct these: a re-solve produces this second's
 *                           answer by construction, and what a suspended core has to
 *                           resume on is last second's.
 *                           An empty array means a save that predates this component,
 *                           on which the restore installs the weights of its own
 *                           re-solve — the behaviour that save already had.
 * @param fuelExcessReactivityDkOverK
 *                           the fuel's excess reactivity with every rod withdrawn,
 *                           dk/k, as the reactivity balance was last given it. The
 *                           fourth frozen output of the same solve — the flux
 *                           weighting is what turns per-assembly k-infinity into
 *                           one core number — and the largest term in the balance
 *                           the {@code reactivityTotal} above was closed on. It is
 *                           weighting-independent only while every assembly has the
 *                           same k-infinity, which is true of a fresh single-fuel
 *                           core and false of every core that has run long enough
 *                           to grow a burnup gradient: on a core at 1039 MWd/t a
 *                           restore recomputed it 5.6e-09 dk/k away from the
 *                           recorded figure and carried the whole of that into
 *                           {@code reactivityTotal}, and on a mixed-fuel core the
 *                           gap was 5.0e-06 dk/k.
 * @param dopplerCoefficientPerCAtAnchor
 *                           the flux-weighted Doppler coefficient the reactivity
 *                           balance was last given, dk/k per degree C, quoted at
 *                           its anchor temperature. Always strictly negative — a
 *                           fuel type is refused at construction unless its
 *                           coefficient is — so <b>zero means a save that predates
 *                           this component</b>, and it is the discriminator for
 *                           this pair: both fall back to being recomputed from the
 *                           loaded fuel, which is the behaviour that save had.
 *                           Frozen and weighting-dependent exactly like the excess
 *                           reactivity beside it, and it moved 2.4e-10 per degree C
 *                           across a mixed-core round trip.
 * @param elapsedSeconds     simulated seconds since core creation
 * @param scramActive        whether the scram signal is latched in. Plant state,
 *                           not a derived flag: it selects the scram insertion
 *                           path — accumulator or reactor-pressure assist, and
 *                           ungated by CRD power and water — and it latches until
 *                           {@code resetScram()}. Dropping it made a save
 *                           <em>cancel</em> a scram in progress: the drives came
 *                           back unlatched at whatever notch they had reached,
 *                           with the demand collapsed onto that same notch, so an
 *                           ATWS on a de-energised CRD bus resumed with the rods
 *                           permanently stopped mid-stroke and the accumulators
 *                           quietly recharging over the evidence.
 * @param intermediateRangeMonitorRanges
 *                           the position of each IRM's range switch, one detent
 *                           number 1..10 per channel, in panel order. Hardware
 *                           state, not a reading: ranging is manual by design
 *                           ({@code SPEC.md} section 9,
 *                           {@link dev.bwr.core.instrument.IntermediateRangeMonitor}),
 *                           so nothing in the plant will put a switch back where
 *                           the operator left it. Dropping this reset every
 *                           channel to detent 1 on each reload, which is
 *                           <em>silent auto-ranging</em> — a mid-startup core
 *                           came back with eight pegged channels reading an
 *                           infinite period, and mis-ranging the IRMs during a
 *                           rod withdrawal is the classic startup accident the
 *                           manual switch exists to make possible.
 *                           An empty array means a save that predates this
 *                           component and leaves the switches wherever they are.
 */
public record ReactorState(
        double neutronPower,
        double[] precursors,
        double sourceStrength,
        double decayHeatFraction,
        double[] decayGroups,
        double fuelTempC,
        double cladTempC,
        double peakCladTempC,
        double peakFuelTempC,
        double oxidationFraction,
        double hydrogenKg,
        double protectiveOxideArealKgPerM2,
        double coolantTempC,
        double pressurePsig,
        double voidFraction,
        double coreInletEnthalpyKJPerKg,
        double coreFlowFraction,
        double waterLevelIn,
        double xenon,
        double iodine,
        double boronPpm,
        double burnupMwdPerTonne,
        int[] rodNotches,
        double[] accumulatorCharge,
        double reactivityTotal,
        double betaEff,
        double promptLifetime,
        double[] rodFluxWeights,
        double fuelExcessReactivityDkOverK,
        double dopplerCoefficientPerCAtAnchor,
        double elapsedSeconds,
        boolean scramActive,
        int[] intermediateRangeMonitorRanges,
        double[] rodPositionsNotches
) {
    /**
     * Defensive copy on construction. These arrays cross the physics/Minecraft
     * boundary and are handed to the peripheral, so aliasing them would let a
     * consumer mutate live core state.
     */
    public ReactorState {
        precursors = precursors == null ? new double[6] : precursors.clone();
        decayGroups = decayGroups == null ? new double[0] : decayGroups.clone();
        rodPositionsNotches = rodPositionsNotches == null ? new double[0] : rodPositionsNotches.clone();
        rodNotches = rodNotches == null ? new int[0] : rodNotches.clone();
        accumulatorCharge = accumulatorCharge == null ? new double[0] : accumulatorCharge.clone();
        rodFluxWeights = rodFluxWeights == null ? new double[0] : rodFluxWeights.clone();
        intermediateRangeMonitorRanges = intermediateRangeMonitorRanges == null
                ? new int[0] : intermediateRangeMonitorRanges.clone();
    }

    @Override
    public double[] precursors() {
        return precursors.clone();
    }

    @Override
    public double[] decayGroups() {
        return decayGroups.clone();
    }

    @Override
    public double[] rodPositionsNotches() { return rodPositionsNotches.clone(); }

    @Override
    public int[] rodNotches() {
        return rodNotches.clone();
    }

    @Override
    public double[] accumulatorCharge() {
        return accumulatorCharge.clone();
    }

    @Override
    public double[] rodFluxWeights() {
        return rodFluxWeights.clone();
    }

    @Override
    public int[] intermediateRangeMonitorRanges() {
        return intermediateRangeMonitorRanges.clone();
    }

    /**
     * Total normalised fission rate: the kinetics term plus decay heat.
     *
     * <p><b>Not the same as {@code ReactorCore.getTotalPowerFractionOfRated()} on
     * fuel that is not ordinary uranium.</b> Both components here are recorded
     * straight off the kinetics and the decay heat inventory, which are normalised
     * to fission rate; turning that into thermal power takes the loaded fuel's
     * recoverable energy per fission, and the record does not carry the fuel —
     * the assemblies are item-side state (SPEC 2.3), deliberately. Ask the core if
     * you want megawatts.
     */
    public double totalPowerFraction() {
        return neutronPower + decayHeatFraction;
    }

    /**
     * Total thermal power in megawatts, on the assumption that the fuel releases
     * the reference energy per fission. Exact for both shipped uranium fuels and
     * an underestimate of a few per cent for plutonium; see
     * {@link #totalPowerFraction()}. {@code ReactorCore.getThermalPowerMW()} knows
     * the fuel and this cannot.
     */
    public double thermalPowerMW() {
        return totalPowerFraction() * PhysicalConstants.RATED_THERMAL_MW;
    }

    /** True when vessel level has fallen below the top of active fuel. */
    public boolean coreUncovered() {
        return waterLevelIn < PhysicalConstants.TAF_ON_INSTRUMENT_SCALE_IN;
    }
}
