package dev.bwr.core.thermal;

import dev.bwr.core.CoreConfig;
import dev.bwr.core.PhysicalConstants;

/**
 * The reactor pressure vessel as one lumped steam dome and one lumped water
 * inventory. {@code SPEC.md} sections 6.2, 6.4 and 15.
 *
 * <h2>Pressure</h2>
 * <pre>
 *   dP/dt = (steam generated - steam removed) / pressure capacity
 * </pre>
 * Steam is generated by core power, less whatever power is spent heating
 * incoming feedwater and injection up to saturation. Steam is removed only
 * through flows the caller passes in.
 *
 * <p>The capacity term is where the physics is:
 * <pre>
 *   capacity = V_dome * drho_g/dP  +  M_liquid * (dh_f/dP) / h_fg     kg per psi
 * </pre>
 * The first term is the steam space filling up. The second is the entire vessel
 * water inventory having to absorb sensible heat as saturation temperature
 * climbs — steam condensing to warm the water it sits on. At rated conditions
 * the first term is 7.3 kg/psi and the second is 52 kg/psi, so <b>the water, not
 * the steam space, is what makes a BWR's pressure response as slow as it is</b>.
 * Model only the dome and an MSIV closure pressurises the vessel eight times too
 * fast. With both, a full-power isolation with no relief gives 33 psi/s, and the
 * same isolation on decay heat alone gives under 3 psi/s.
 *
 * <h2>No relief logic lives here</h2>
 * {@link #step} takes turbine, bypass and relief flows as arguments and adds
 * them up. <b>Safety and relief valves are player-actuated</b> through
 * CC:Tweaked or redstone, per the project's control philosophy: this class has
 * no setpoints, opens nothing by itself, and cannot tell the difference between
 * a relief flow and a bypass flow except in the readout label.
 * {@link PhysicalConstants#SRV_SPRING_SETTINGS_PSIG} records what the real
 * valves are rated at; deciding when to lift them is Lua's job.
 *
 * <h2>Level, and the trap</h2>
 * Three different level numbers, and the distance between them is the whole
 * point:
 * <ul>
 *   <li>{@link #getCollapsedLevelIn()} — where the water would be with every
 *       bubble squeezed out. Follows inventory and nothing else. This is the
 *       honest number, and it is the one the fuel feels.</li>
 *   <li>{@link #getTwoPhaseLevelIn()} — collapsed level plus the volume the
 *       voids displace. The actual free surface.</li>
 *   <li>{@link #getIndicatedLevelIn()} — what the instrument says, which is the
 *       two-phase level distorted by a differential-pressure cell that was
 *       calibrated for saturated water at 1025 psig with a 135 degF drywell
 *       [TTC 3.1.2.1.1] and has no idea those conditions have changed.</li>
 * </ul>
 *
 * <p><b>The classic operator trap falls out of this without being scripted.</b>
 * Drop the pressure and three things happen at once: water flashes to steam so
 * inventory genuinely falls; the extra voids swell the two-phase level upward;
 * and the now-denser water in the variable leg makes the instrument read high on
 * top of that. <b>Indicated level rises while the vessel is emptying.</b> Run it
 * the other way — an MSIV closure — and the void collapse drops indicated level
 * sharply even though inventory is climbing, which is the shrink that follows
 * every scram.
 *
 * <p>All levels are inches on the instrument-zero scale, matching
 * {@link PhysicalConstants#TAF_ON_INSTRUMENT_SCALE_IN}. Negative is below
 * instrument zero.
 *
 * <h2>Tick order</h2>
 * Update {@link VoidModel} first with last tick's pressure, run the kinetics
 * against frozen void and pressure, then step this once per tick with the new
 * void fraction. {@code SPEC.md} section 6.3 requires exactly that ordering:
 * the pressure-to-void-to-power loop is fast and positive-feedback-capable, and
 * integrating it at sub-step resolution against a thermal model that only has
 * tick resolution invents oscillations that are not there.
 *
 * <p>Pure Java, doubles, no Minecraft. Not thread safe.
 */
public final class PressureVessel {

    // ---------------------------------------------------------------
    // Geometry [TTC 1.8, 3.1.2.1]
    // ---------------------------------------------------------------

    /** Metres per inch. */
    public static final double METRES_PER_INCH = 0.0254;

    /** Reactor vessel inside diameter, inches [TTC 1.8]. */
    public static final double VESSEL_INSIDE_DIAMETER_IN = 238.0;

    /** Gross vessel cross-sectional area, m2 — 28.7 m2 at 238 in inside diameter. */
    public static final double VESSEL_GROSS_AREA_M2 =
            Math.PI * 0.25 * Math.pow(VESSEL_INSIDE_DIAMETER_IN * METRES_PER_INCH, 2.0);

    /** Active fuel length, inches. A BWR fuel bundle is 150 in of fuel column. */
    public static final double ACTIVE_FUEL_HEIGHT_IN = 150.0;

    /** Bottom of active fuel on the instrument-zero scale, inches: TAF less the fuel length. */
    public static final double BAF_ON_INSTRUMENT_SCALE_IN =
            PhysicalConstants.TAF_ON_INSTRUMENT_SCALE_IN - ACTIVE_FUEL_HEIGHT_IN; // -317

    /**
     * Collapsed level at the normal operating condition, inches on the
     * instrument-zero scale.
     *
     * <p>Normal <i>indicated</i> level sits near +30 in, in the middle of the
     * 0 to +60 in narrow range [TTC 3.1.2.1]. About 22 in of that is void swell
     * at rated power, so the collapsed level underneath is near +8. Used to
     * derive {@link #getLevelAreaM2()} and by {@link #initialiseToNormalLevel}.
     */
    public static final double NORMAL_COLLAPSED_LEVEL_IN = 8.0;

    /**
     * Volume of the two-phase (boiling) region, m3 — core plus upper plenum and
     * standpipes, the part of the vessel where voids exist and displace water
     * upward.
     *
     * <p>Derived: 748 assemblies of 5.5 in pitch over 150 in of active fuel is
     * about 55 m3 gross, roughly 40% of which is coolant, plus the upper plenum.
     * At 33 m3 and a rated core-average void fraction of 0.371, the swell is
     * 22.0 in, which is the gap between collapsed and indicated level a BWR
     * actually runs with — and it is the whole of the level shrink that follows
     * a scram, since the voids vanish and the water does not.
     */
    public static final double DEFAULT_TWO_PHASE_REGION_VOLUME_M3 = 33.0;

    // ---------------------------------------------------------------
    // Level instrument [TTC 3.1.2.1.1]
    // ---------------------------------------------------------------

    /** Lower sensing tap of the wide-range level instrument, inches on the instrument scale. */
    public static final double DEFAULT_BOTTOM_TAP_IN = -320.0;

    /**
     * Height of the wet reference leg, metres — from the lower tap up to the
     * condensing pot at the upper tap, 380 in apart.
     */
    public static final double DEFAULT_REFERENCE_LEG_HEIGHT_M = 380.0 * METRES_PER_INCH;

    /**
     * Drywell temperature the reference leg is calibrated at, degrees C —
     * 135 degF [TTC 3.1.2.1.1].
     *
     * <p>This calibration is the physical basis for the level error: the
     * instrument assumes the reference leg is full of water at this temperature
     * and the vessel is full of saturated water at rated pressure. Let the
     * drywell heat up and the reference leg gets lighter, so the cell sees less
     * back-pressure and the indication climbs — a real accident-condition
     * failure of level indication, and one with history.
     */
    public static final double CALIBRATION_DRYWELL_TEMPERATURE_C = 57.222;

    /** Vessel pressure the level instrument is calibrated at, psig. Rated dome pressure. */
    public static final double CALIBRATION_PRESSURE_PSIG = PhysicalConstants.RATED_DOME_PRESSURE_PSIG;

    // ---------------------------------------------------------------
    // Integration guards
    // ---------------------------------------------------------------

    /**
     * Pressure change per sub-step above which {@link #step} subdivides,
     * psi. Pressure is integrated explicitly because the fluid properties on
     * both sides of the balance move with it; sub-dividing keeps those
     * properties current. An accuracy knob, not a stability one.
     */
    public static final double MAX_PRESSURE_STEP_PSI = 5.0;

    /** Ceiling on sub-steps per {@link #step}, bounding worst-case tick cost. */
    public static final int MAX_PRESSURE_SUB_STEPS = 64;

    /**
     * Numerical floor on dome pressure, psig — a hard vacuum, well below any
     * condition the plant reaches. Guards the power-law correlations, which need
     * a positive absolute pressure.
     */
    public static final double MINIMUM_PRESSURE_PSIG =
            Saturation.MINIMUM_PRESSURE_PSIA - PhysicalConstants.ATMOSPHERIC_PSI;

    /**
     * Numerical ceiling on dome pressure, psig. Set far above the 1375 psig ASME
     * code limit so the overpressure damage model gets to decide what failure
     * looks like; this only stops an unbounded double from poisoning the state.
     *
     * <p>It is not a free clamp. Dome steam mass in this model is
     * {@code V_dome * rho_g(P)}, so pinning P pins the dome inventory, and if
     * boiling and steam removal carried on at full rate against a pinned dome the
     * vessel would destroy mass at the ceiling and fabricate it at the floor. The
     * cure is in {@link #step}: whatever fraction of the requested pressure change
     * the clamp refuses, the same fraction of the mass transfer is refused with
     * it. See the comment there before changing either.
     */
    public static final double MAXIMUM_PRESSURE_PSIG = 5000.0;

    // ---------------------------------------------------------------
    // Configuration
    // ---------------------------------------------------------------

    private final CoreConfig config;

    private double steamDomeVolumeM3;
    private double levelAreaM2;
    private double twoPhaseRegionVolumeM3 = DEFAULT_TWO_PHASE_REGION_VOLUME_M3;
    private double bottomTapIn = DEFAULT_BOTTOM_TAP_IN;
    private double referenceLegHeightM = DEFAULT_REFERENCE_LEG_HEIGHT_M;
    private double drywellTemperatureC = CALIBRATION_DRYWELL_TEMPERATURE_C;

    // --- commanded water-side flows (actuators the caller drives) -------

    private double feedwaterFlowKgPerS;
    private double feedwaterEnthalpyKJPerKg = VoidModel.DEFAULT_FEEDWATER_ENTHALPY_KJ_PER_KG;
    private double injectionFlowKgPerS;
    private double injectionEnthalpyKJPerKg = Saturation.subcooledLiquidEnthalpyKJPerKg(40.0);
    private double liquidLeakKgPerS;
    private double steamLeakKgPerS;

    // --- state ----------------------------------------------------------

    private double pressurePsig = PhysicalConstants.RATED_DOME_PRESSURE_PSIG;
    private double liquidMassKg;

    // --- last computed ---------------------------------------------------

    private double pressureRateOfChangePsiPerSecond;
    private double steamGenerationKgPerS;
    private double steamRemovalKgPerS;
    private double commandedSteamRemovalKgPerS;
    private double flashingKgPerS;
    private double pressureCapacityKgPerPsi;
    private double coreVoidFraction;
    private double collapsedLevelIn;
    private double twoPhaseLevelIn;
    private double indicatedLevelIn;
    private double levelSwellIn;
    private double instrumentErrorIn;

    /**
     * @param config supplies the steam dome volume and the nominal coolant mass.
     *               The level area is derived from that mass so the two agree:
     *               2.2e5 kg of saturated water at rated pressure is 300 m3,
     *               which over the 538 in from vessel zero to the normal
     *               collapsed level is 22.0 m2 of free surface. That is the
     *               gross 28.7 m2 vessel section less about a quarter for core,
     *               shroud and separator internals, so the config and the
     *               geometry are consistent rather than independently guessed.
     */
    public PressureVessel(CoreConfig config) {
        if (config == null) {
            throw new IllegalArgumentException("config must not be null");
        }
        this.config = config;
        this.steamDomeVolumeM3 = config.steamDomeVolumeM3;

        double ratedPsia = Saturation.psiaFromPsig(PhysicalConstants.RATED_DOME_PRESSURE_PSIG);
        double nominalVolumeM3 = config.coolantMassKg / Saturation.liquidDensityKgPerM3(ratedPsia);
        double heightM = (PhysicalConstants.INSTRUMENT_ZERO_ABOVE_VESSEL_ZERO_IN
                + NORMAL_COLLAPSED_LEVEL_IN) * METRES_PER_INCH;
        this.levelAreaM2 = nominalVolumeM3 / heightM;

        this.liquidMassKg = config.coolantMassKg;
        recomputeLevels();
    }

    // ---------------------------------------------------------------
    // Step
    // ---------------------------------------------------------------

    /**
     * Advance pressure, inventory and level one tick.
     *
     * <p>The three steam flows are separate arguments rather than one total
     * because they are three different actuators the player operates
     * independently and each needs its own readback. The model adds them; it
     * does not care which is which.
     *
     * @param coreThermalMW      total core thermal power, MW — fission plus decay
     *                           heat. Decay heat boils water, so a scrammed core
     *                           is still a steam source.
     * @param coreVoidFraction   core-average void fraction from {@link VoidModel},
     *                           0..1. Sets level swell.
     * @param turbineSteamFlowKgPerS  steam to the turbine control valves
     * @param bypassSteamFlowKgPerS   steam to the turbine bypass valves
     * @param reliefSteamFlowKgPerS   steam through safety/relief valves the
     *                           player has opened. Nothing in this class opens
     *                           them.
     * @param dtSeconds          step length, seconds; non-positive is a no-op
     * @return the new dome pressure, psig
     */
    public double step(double coreThermalMW,
                       double coreVoidFraction,
                       double turbineSteamFlowKgPerS,
                       double bypassSteamFlowKgPerS,
                       double reliefSteamFlowKgPerS,
                       double dtSeconds) {
        this.coreVoidFraction = clamp(coreVoidFraction, 0.0, 1.0);
        if (!(dtSeconds > 0.0) || !Double.isFinite(dtSeconds)) {
            recomputeLevels();
            return pressurePsig;
        }

        double thermalKW = Math.max(0.0, finite(coreThermalMW)) * 1000.0;
        double steamOut = nonNegative(turbineSteamFlowKgPerS)
                + nonNegative(bypassSteamFlowKgPerS)
                + nonNegative(reliefSteamFlowKgPerS)
                + nonNegative(steamLeakKgPerS);
        this.commandedSteamRemovalKgPerS = steamOut;

        int subSteps = chooseSubSteps(thermalKW, steamOut, dtSeconds);
        double dt = dtSeconds / subSteps;

        double startPressure = pressurePsig;
        double lastBoiling = 0.0;
        double lastSteamOut = 0.0;
        double lastFlashing = 0.0;
        double lastCapacity = 0.0;

        for (int s = 0; s < subSteps; s++) {
            double psia = Saturation.psiaFromPsig(pressurePsig);
            double liquidEnthalpy = Saturation.liquidEnthalpyKJPerKg(psia);
            double latentHeat = Saturation.latentHeatKJPerKg(psia);
            double liquidEnthalpySlope = Saturation.liquidEnthalpySlopeKJPerKgPerPsi(psia);
            double vapourDensitySlope = Saturation.vapourDensitySlopeKgPerM3PerPsi(psia);

            double feedwater = nonNegative(feedwaterFlowKgPerS);
            double injection = nonNegative(injectionFlowKgPerS);

            // Power spent dragging cold water up to saturation is power that
            // does not make steam. At rated this is 688 MW of the 3579, which is
            // why 3579 MW produces 1941 kg/s of steam and not 2402.
            double heatingDutyKW = feedwater * (liquidEnthalpy - feedwaterEnthalpyKJPerKg)
                    + injection * (liquidEnthalpy - injectionEnthalpyKJPerKg);

            // Deliberately allowed to go negative: injecting cold water faster
            // than the core can reheat it condenses steam and depressurises the
            // vessel, which is real and is how a cold ECCS injection kills
            // pressure.
            double boiling = (thermalKW - heatingDutyKW) / latentHeat;
            if (boiling > 0.0 && boiling * dt > liquidMassKg) {
                boiling = liquidMassKg / dt; // cannot boil water that is not there
            }

            // Sensible heat storage of the water inventory, expressed as the
            // steam mass that must condense per psi of pressure rise.
            double liquidCapacityKgPerPsi = liquidMassKg * liquidEnthalpySlope / latentHeat;
            double capacity = steamDomeVolumeM3 * vapourDensitySlope + liquidCapacityKgPerPsi;
            if (!(capacity > 0.0)) {
                capacity = steamDomeVolumeM3 * vapourDensitySlope;
            }

            double rate = (boiling - steamOut) / capacity;
            double requestedPressure = pressurePsig + rate * dt;
            double newPressure = clamp(requestedPressure,
                    MINIMUM_PRESSURE_PSIG, MAXIMUM_PRESSURE_PSIG);
            double appliedRate = (newPressure - pressurePsig) / dt;
            pressurePsig = newPressure;

            // ---- mass conservation across the pressure clamp ----
            //
            // Dome steam mass here is not an independent state: it is
            // V_dome * rho_g(P), so the only way steam mass changes is for
            // pressure to change. The balance that makes the vessel conserve mass
            // is
            //
            //   d(dome steam)/dt = boiling + flashing - steamOut
            //
            // and with flashing = -liquidCapacity * rate it closes exactly,
            // because capacity = domeCapacity + liquidCapacity. Now let the clamp
            // refuse part of the requested dP. flashing follows appliedRate and so
            // shrinks with it, and so does the dome term — but boiling and
            // steamOut do not, and the balance breaks by exactly the refused
            // fraction. At the ceiling that fraction of the boiled water was
            // subtracted from the liquid and added to nothing (187 tonnes lost in
            // 75 s with every valve shut); at the floor that fraction of steamOut
            // left a dome that never gave it up (237 tonnes of steam from nothing
            // in 600 s).
            //
            // So: accept the mass transfer in the same proportion the pressure
            // change was accepted. Scaling boiling and steamOut by the same factor
            // keeps boiling - steamOut = accepted * (boiling - steamOut), which is
            // precisely what the accepted dP corresponds to, and the balance
            // closes again. Physically the ceiling means the vessel stops taking
            // energy and the floor means an open valve passes nothing because
            // there is nothing left to pass — both are more honest than a leak.
            //
            // The unclamped case is tested for exactly rather than derived, so
            // that the overwhelmingly common step multiplies by a literal 1.0 and
            // is bit-for-bit what it was before this scaling existed.
            // appliedRate / rate is not exactly 1.0 even when nothing was
            // clamped, because (P + rate*dt) - P does not round back to rate*dt,
            // and a save/restore comparison that demands bit equality would see
            // that 1e-12 and be right to.
            double accepted = 1.0;
            if (newPressure != requestedPressure) {
                accepted = (rate == 0.0) ? 1.0 : clamp(appliedRate / rate, 0.0, 1.0);
            }
            double acceptedBoiling = boiling * accepted;
            double acceptedSteamOut = steamOut * accepted;

            // The same sensible-heat term seen as mass transfer. Pressure down,
            // water flashes to steam; pressure up, steam condenses back into the
            // water. Signs are opposite because the liquid is the reservoir.
            double flashing = -liquidCapacityKgPerPsi * appliedRate;

            double liquidChange = (nonNegative(feedwaterFlowKgPerS)
                    + nonNegative(injectionFlowKgPerS)
                    - acceptedBoiling
                    - flashing
                    - nonNegative(liquidLeakKgPerS)) * dt;
            liquidMassKg = Math.max(0.0, liquidMassKg + liquidChange);

            lastBoiling = acceptedBoiling;
            lastSteamOut = acceptedSteamOut;
            lastFlashing = flashing;
            lastCapacity = capacity;
        }

        this.steamGenerationKgPerS = lastBoiling;
        this.steamRemovalKgPerS = lastSteamOut;
        this.flashingKgPerS = lastFlashing;
        this.pressureCapacityKgPerPsi = lastCapacity;
        this.pressureRateOfChangePsiPerSecond = (pressurePsig - startPressure) / dtSeconds;

        recomputeLevels();
        return pressurePsig;
    }

    /**
     * Picks a sub-step count from a first-order estimate of the pressure change
     * over the tick, so a violent transient is resolved and a quiet one costs a
     * single pass.
     */
    private int chooseSubSteps(double thermalKW, double steamOutKgPerS, double dtSeconds) {
        double psia = Saturation.psiaFromPsig(pressurePsig);
        double latentHeat = Saturation.latentHeatKJPerKg(psia);
        double capacity = steamDomeVolumeM3 * Saturation.vapourDensitySlopeKgPerM3PerPsi(psia)
                + liquidMassKg * Saturation.liquidEnthalpySlopeKJPerKgPerPsi(psia) / latentHeat;
        if (!(capacity > 0.0)) {
            return 1;
        }
        double estimate = Math.abs((thermalKW / latentHeat - steamOutKgPerS) / capacity) * dtSeconds;
        int steps = (int) Math.ceil(estimate / MAX_PRESSURE_STEP_PSI);
        return Math.max(1, Math.min(MAX_PRESSURE_SUB_STEPS, steps));
    }

    // ---------------------------------------------------------------
    // Level
    // ---------------------------------------------------------------

    private void recomputeLevels() {
        double psia = Saturation.psiaFromPsig(pressurePsig);
        double liquidDensity = Saturation.liquidDensityKgPerM3(psia);

        double liquidVolumeM3 = liquidMassKg / liquidDensity;
        double collapsedHeightM = liquidVolumeM3 / levelAreaM2;
        this.collapsedLevelIn = collapsedHeightM / METRES_PER_INCH
                - PhysicalConstants.INSTRUMENT_ZERO_ABOVE_VESSEL_ZERO_IN;

        // Voids only swell the level while there is a boiling region under
        // water to hold them. Below the top of active fuel the swell fades out,
        // reaching zero at the bottom of the fuel — an empty vessel cannot swell.
        double submergedFraction = clamp(
                (collapsedLevelIn - BAF_ON_INSTRUMENT_SCALE_IN) / ACTIVE_FUEL_HEIGHT_IN, 0.0, 1.0);
        double swellVolumeM3 = coreVoidFraction * twoPhaseRegionVolumeM3 * submergedFraction;
        this.levelSwellIn = swellVolumeM3 / levelAreaM2 / METRES_PER_INCH;
        this.twoPhaseLevelIn = collapsedLevelIn + levelSwellIn;

        // Differential-pressure level indication.
        //
        //   L_indicated = H_ref * (rho_ref_cal - rho_ref) / rho_var_cal
        //               + L_true * rho_var / rho_var_cal
        //
        // At the calibration densities both correction factors are unity and the
        // instrument reads true. Away from them it does not, and it has no way
        // of knowing: a DP cell measures a pressure difference and divides by
        // the density it was told about at the factory.
        double calibrationPsia = Saturation.psiaFromPsig(CALIBRATION_PRESSURE_PSIG);
        double variableDensityCalibration = Saturation.liquidDensityKgPerM3(calibrationPsia);
        double referenceDensityCalibration =
                Saturation.liquidDensityFromTemperatureKgPerM3(CALIBRATION_DRYWELL_TEMPERATURE_C);
        double referenceDensity =
                Saturation.liquidDensityFromTemperatureKgPerM3(drywellTemperatureC);

        // The variable leg is bounded by the instrument's own taps at both ends.
        // Below the lower tap the cell sees no column at all and the reading
        // bottoms out; above the upper tap it sees a solid column and cannot see
        // any more, so the reading pegs. With the defaults the taps are 380 in
        // apart from -320 in, putting the upper one at +60 in — the top of the
        // wide range. Leaving the top open let an overfill read +400 in on an
        // instrument that physically stops at +60, which is the one way this
        // model was wrong that a real DP cell is not: coping with a channel that
        // has pegged and stopped telling you anything is exactly what a flood-up
        // procedure is for.
        double trueHeightAboveTapM = clamp((twoPhaseLevelIn - bottomTapIn) * METRES_PER_INCH,
                0.0, referenceLegHeightM);
        double referenceLegTermM = referenceLegHeightM
                * (referenceDensityCalibration - referenceDensity) / variableDensityCalibration;
        double variableLegTermM = trueHeightAboveTapM * liquidDensity / variableDensityCalibration;

        this.indicatedLevelIn = bottomTapIn + (referenceLegTermM + variableLegTermM) / METRES_PER_INCH;
        this.instrumentErrorIn = indicatedLevelIn - twoPhaseLevelIn;
    }

    // ---------------------------------------------------------------
    // Pressure readouts
    // ---------------------------------------------------------------

    /** Reactor steam dome pressure, psig. */
    public double getPressurePsig() {
        return pressurePsig;
    }

    /** Reactor steam dome pressure, psia. */
    public double getPressurePsia() {
        return Saturation.psiaFromPsig(pressurePsig);
    }

    /**
     * Bulk coolant temperature, degrees C, read off the saturation curve. The
     * vessel is saturated, so this is not an independent state: it is pressure
     * wearing a different unit. 287.4 degC at rated.
     */
    public double getSaturationTemperatureC() {
        return Saturation.temperatureCelsiusFromPsig(pressurePsig);
    }

    /** Bulk coolant temperature, degrees F. */
    public double getSaturationTemperatureF() {
        return Saturation.temperatureFahrenheitFromPsig(pressurePsig);
    }

    /** Rate of change of dome pressure over the last step, psi per second. */
    public double getPressureRateOfChangePsiPerSecond() {
        return pressureRateOfChangePsiPerSecond;
    }

    /**
     * Steam mass the dome must accumulate or shed per psi of pressure change,
     * kg/psi. About 59 kg/psi at rated conditions, of which 52 is the water
     * inventory's sensible heat.
     */
    public double getPressureCapacityKgPerPsi() {
        return pressureCapacityKgPerPsi;
    }

    // ---------------------------------------------------------------
    // Mass flow readouts
    // ---------------------------------------------------------------

    /**
     * Net steam generation rate, kg/s — boiling driven by core power less the
     * duty of heating incoming water to saturation. About 1941 kg/s at rated,
     * against a plant rated steam flow of 15.4e6 lb/hr = 1941 kg/s [TTC 1.8].
     *
     * <p>Negative when cold injection is condensing more steam than the core is
     * making, which is the mechanism behind an injection-driven depressurisation.
     */
    public double getSteamGenerationKgPerS() {
        return steamGenerationKgPerS;
    }

    /**
     * Total steam that actually left the vessel over the last step, kg/s.
     *
     * <p>Normally this is exactly what the caller asked for: turbine plus bypass
     * plus relief plus any steam leak. It falls below that only when the dome
     * pressure hit {@link #MINIMUM_PRESSURE_PSIG} or
     * {@link #MAXIMUM_PRESSURE_PSIG} part way through the step, because a pinned
     * pressure is a pinned dome inventory and a valve cannot pass steam the dome
     * no longer has. Use {@link #getCommandedSteamRemovalKgPerS()} for the flow
     * that was asked for; this one is the mass that moved, and it is this one
     * that balances against the change in inventory.
     */
    public double getSteamRemovalKgPerS() {
        return steamRemovalKgPerS;
    }

    /**
     * Sum of the steam flows the caller commanded on the last step, kg/s:
     * turbine plus bypass plus relief plus any steam leak, before the pressure
     * floor or ceiling has had a say. Equal to
     * {@link #getSteamRemovalKgPerS()} everywhere except against a pinned
     * pressure.
     */
    public double getCommandedSteamRemovalKgPerS() {
        return commandedSteamRemovalKgPerS;
    }

    /**
     * Liquid-to-vapour mass transfer driven purely by the pressure change, kg/s.
     * Positive when the vessel is depressurising and water is flashing; negative
     * when it is pressurising and steam is condensing back.
     */
    public double getFlashingKgPerS() {
        return flashingKgPerS;
    }

    /** Water inventory in the vessel, kg. */
    public double getLiquidMassKg() {
        return liquidMassKg;
    }

    /** Steam mass held in the dome, kg — dome volume times saturated vapour density. */
    public double getSteamMassKg() {
        return steamDomeVolumeM3 * Saturation.vapourDensityKgPerM3(getPressurePsia());
    }

    // ---------------------------------------------------------------
    // Level readouts
    // ---------------------------------------------------------------

    /**
     * Collapsed water level, inches on the instrument-zero scale — the level
     * with every void squeezed out. Tracks inventory and nothing else, so this
     * is the number that says whether the fuel is covered. About +8 in at the
     * normal operating condition.
     */
    public double getCollapsedLevelIn() {
        return collapsedLevelIn;
    }

    /**
     * Actual two-phase free surface, inches on the instrument-zero scale:
     * collapsed level plus the volume the voids displace. About +30 in at rated.
     */
    public double getTwoPhaseLevelIn() {
        return twoPhaseLevelIn;
    }

    /**
     * What the level instrument reads, inches on the instrument-zero scale.
     *
     * <p>This is the only level a control program should be given. It is wrong
     * during pressure and drywell temperature transients, and being wrong in
     * exactly the way a real DP cell is wrong is the point.
     *
     * <p>It also <b>pegs</b>. The cell can only see between its two taps, so once
     * the water is above the upper tap — +60 in with the default geometry — the
     * reading stops moving no matter how much further the vessel is overfilled.
     * A level controller written against this has to notice that for itself.
     */
    public double getIndicatedLevelIn() {
        return indicatedLevelIn;
    }

    /** Void swell contribution to level, inches. About +22 in at rated power. */
    public double getLevelSwellIn() {
        return levelSwellIn;
    }

    /**
     * Difference between indicated and true two-phase level, inches. Positive
     * means the instrument is reading high. Zero at the calibration conditions.
     *
     * <p>Model diagnostic, for tests and CSV dumps. Do not publish it to the
     * peripheral: an instrument that reports its own error is not an instrument.
     */
    public double getInstrumentErrorIn() {
        return instrumentErrorIn;
    }

    /** Collapsed level relative to the top of active fuel, inches. Negative once uncovered. */
    public double getLevelAboveTopOfActiveFuelIn() {
        return collapsedLevelIn - PhysicalConstants.TAF_ON_INSTRUMENT_SCALE_IN;
    }

    /**
     * Fraction of the active fuel height still under water, 0..1, from the
     * collapsed level. Feed this to {@link FuelThermal}: the fuel is cooled by
     * the water that is actually there, not by the swelled two-phase level and
     * certainly not by what the instrument claims.
     */
    public double getCoveredFuelFraction() {
        return 1.0 - getUncoveredFuelFraction();
    }

    /** Fraction of the active fuel height above the collapsed level, 0..1. */
    public double getUncoveredFuelFraction() {
        return clamp((PhysicalConstants.TAF_ON_INSTRUMENT_SCALE_IN - collapsedLevelIn)
                / ACTIVE_FUEL_HEIGHT_IN, 0.0, 1.0);
    }

    // ---------------------------------------------------------------
    // Water-side actuators
    // ---------------------------------------------------------------

    /** Feedwater flow into the vessel, kg/s. The normal level control path, SPEC 15. */
    public void setFeedwaterFlowKgPerS(double feedwaterFlowKgPerS) {
        this.feedwaterFlowKgPerS = nonNegative(feedwaterFlowKgPerS);
    }

    public double getFeedwaterFlowKgPerS() {
        return feedwaterFlowKgPerS;
    }

    /** Feedwater enthalpy, kJ/kg. Colder feedwater costs more core power to heat. */
    public void setFeedwaterEnthalpyKJPerKg(double feedwaterEnthalpyKJPerKg) {
        this.feedwaterEnthalpyKJPerKg = nonNegative(feedwaterEnthalpyKJPerKg);
    }

    public double getFeedwaterEnthalpyKJPerKg() {
        return feedwaterEnthalpyKJPerKg;
    }

    /** Convenience: set feedwater enthalpy from a temperature in degrees C. */
    public void setFeedwaterTemperatureC(double temperatureC) {
        setFeedwaterEnthalpyKJPerKg(Saturation.subcooledLiquidEnthalpyKJPerKg(temperatureC));
    }

    /**
     * Emergency injection flow into the vessel, kg/s — RCIC, HPCI, HPCS, LPCI,
     * core spray, CRD purge, whatever the player has running. Summed by the
     * caller; this class does not know which system it came from and has no
     * opinion about whether it should be running.
     */
    public void setInjectionFlowKgPerS(double injectionFlowKgPerS) {
        this.injectionFlowKgPerS = nonNegative(injectionFlowKgPerS);
    }

    public double getInjectionFlowKgPerS() {
        return injectionFlowKgPerS;
    }

    /** Injection enthalpy, kJ/kg. Defaults to about 40 degC — suppression pool or tank water. */
    public void setInjectionEnthalpyKJPerKg(double injectionEnthalpyKJPerKg) {
        this.injectionEnthalpyKJPerKg = nonNegative(injectionEnthalpyKJPerKg);
    }

    public double getInjectionEnthalpyKJPerKg() {
        return injectionEnthalpyKJPerKg;
    }

    /** Convenience: set injection enthalpy from a temperature in degrees C. */
    public void setInjectionTemperatureC(double temperatureC) {
        setInjectionEnthalpyKJPerKg(Saturation.subcooledLiquidEnthalpyKJPerKg(temperatureC));
    }

    /** Liquid leaving through a break below the water line, kg/s. A recirculation-line LOCA. */
    public void setLiquidLeakKgPerS(double liquidLeakKgPerS) {
        this.liquidLeakKgPerS = nonNegative(liquidLeakKgPerS);
    }

    public double getLiquidLeakKgPerS() {
        return liquidLeakKgPerS;
    }

    /** Steam leaving through a break in the steam space, kg/s. A steam-line break. */
    public void setSteamLeakKgPerS(double steamLeakKgPerS) {
        this.steamLeakKgPerS = nonNegative(steamLeakKgPerS);
    }

    public double getSteamLeakKgPerS() {
        return steamLeakKgPerS;
    }

    // ---------------------------------------------------------------
    // Configuration
    // ---------------------------------------------------------------

    /** Steam dome volume, m3. Sets how sharply pressure answers a flow mismatch. */
    public double getSteamDomeVolumeM3() {
        return steamDomeVolumeM3;
    }

    /** @see #getSteamDomeVolumeM3() */
    public void setSteamDomeVolumeM3(double steamDomeVolumeM3) {
        if (!(steamDomeVolumeM3 > 0.0) || !Double.isFinite(steamDomeVolumeM3)) {
            throw new IllegalArgumentException(
                    "steam dome volume must be finite and positive, got " + steamDomeVolumeM3);
        }
        this.steamDomeVolumeM3 = steamDomeVolumeM3;
    }

    /** Free surface area used to convert water volume to level, m2. About 22 m2. */
    public double getLevelAreaM2() {
        return levelAreaM2;
    }

    /** @see #getLevelAreaM2() */
    public void setLevelAreaM2(double levelAreaM2) {
        if (!(levelAreaM2 > 0.0) || !Double.isFinite(levelAreaM2)) {
            throw new IllegalArgumentException(
                    "level area must be finite and positive, got " + levelAreaM2);
        }
        this.levelAreaM2 = levelAreaM2;
        recomputeLevels();
    }

    /** Volume of the boiling region whose voids swell the level, m3. */
    public double getTwoPhaseRegionVolumeM3() {
        return twoPhaseRegionVolumeM3;
    }

    /** @see #getTwoPhaseRegionVolumeM3() */
    public void setTwoPhaseRegionVolumeM3(double twoPhaseRegionVolumeM3) {
        if (!(twoPhaseRegionVolumeM3 >= 0.0) || !Double.isFinite(twoPhaseRegionVolumeM3)) {
            throw new IllegalArgumentException(
                    "two phase region volume must be finite and non-negative, got "
                            + twoPhaseRegionVolumeM3);
        }
        this.twoPhaseRegionVolumeM3 = twoPhaseRegionVolumeM3;
        recomputeLevels();
    }

    /**
     * Drywell temperature the reference leg sits in, degrees C. Raise it and the
     * level instrument starts reading high, because the reference leg it is
     * subtracting has got lighter than the calibration assumed.
     */
    public double getDrywellTemperatureC() {
        return drywellTemperatureC;
    }

    /** @see #getDrywellTemperatureC() */
    public void setDrywellTemperatureC(double drywellTemperatureC) {
        this.drywellTemperatureC = finite(drywellTemperatureC);
        recomputeLevels();
    }

    /** Lower sensing tap elevation, inches on the instrument-zero scale. */
    public double getBottomTapIn() {
        return bottomTapIn;
    }

    /** @see #getBottomTapIn() */
    public void setBottomTapIn(double bottomTapIn) {
        this.bottomTapIn = finite(bottomTapIn);
        recomputeLevels();
    }

    /** Wet reference leg height, metres. */
    public double getReferenceLegHeightM() {
        return referenceLegHeightM;
    }

    /** @see #getReferenceLegHeightM() */
    public void setReferenceLegHeightM(double referenceLegHeightM) {
        if (!(referenceLegHeightM >= 0.0) || !Double.isFinite(referenceLegHeightM)) {
            throw new IllegalArgumentException(
                    "reference leg height must be finite and non-negative, got " + referenceLegHeightM);
        }
        this.referenceLegHeightM = referenceLegHeightM;
        recomputeLevels();
    }

    // ---------------------------------------------------------------
    // Initialisation and persistence
    // ---------------------------------------------------------------

    /**
     * Put the vessel at rated pressure with the collapsed level at
     * {@link #NORMAL_COLLAPSED_LEVEL_IN}, for a run that starts hot.
     */
    public void initialiseToNormalLevel() {
        this.pressurePsig = PhysicalConstants.RATED_DOME_PRESSURE_PSIG;
        this.liquidMassKg = config.coolantMassKg;
        recomputeLevels();
    }

    /**
     * Set water inventory from a desired collapsed level, inches on the
     * instrument-zero scale. Useful for tests and for staging an accident.
     */
    public void setCollapsedLevelIn(double collapsedLevelIn) {
        double heightM = (finite(collapsedLevelIn)
                + PhysicalConstants.INSTRUMENT_ZERO_ABOVE_VESSEL_ZERO_IN) * METRES_PER_INCH;
        double volumeM3 = Math.max(0.0, heightM) * levelAreaM2;
        this.liquidMassKg = volumeM3 * Saturation.liquidDensityKgPerM3(getPressurePsia());
        recomputeLevels();
    }

    /** Restore persisted dome pressure, psig. Persistence only. */
    public void restorePressurePsig(double pressurePsig) {
        this.pressurePsig = clamp(finite(pressurePsig), MINIMUM_PRESSURE_PSIG, MAXIMUM_PRESSURE_PSIG);
        recomputeLevels();
    }

    /** Restore persisted water inventory, kg. Persistence only. */
    public void restoreLiquidMassKg(double liquidMassKg) {
        this.liquidMassKg = Math.max(0.0, finite(liquidMassKg));
        recomputeLevels();
    }

    // ---------------------------------------------------------------
    // Helpers
    // ---------------------------------------------------------------

    private static double finite(double value) {
        return Double.isFinite(value) ? value : 0.0;
    }

    private static double nonNegative(double value) {
        return (Double.isFinite(value) && value > 0.0) ? value : 0.0;
    }

    private static double clamp(double value, double minimum, double maximum) {
        if (!Double.isFinite(value)) {
            return minimum;
        }
        return Math.min(maximum, Math.max(minimum, value));
    }

    @Override
    public String toString() {
        return String.format(
                "PressureVessel[%.1f psig / %.1f degC, level ind %.1f / two-phase %.1f / collapsed %.1f in,"
                        + " %.0f kg water, steam %+.0f kg/s]",
                pressurePsig, getSaturationTemperatureC(), indicatedLevelIn, twoPhaseLevelIn,
                collapsedLevelIn, liquidMassKg, steamGenerationKgPerS - steamRemovalKgPerS);
    }
}
